### ISSUE TITLE
Feature. Allow AWS SRT role custom name

### ISSUE THREAD

**Issue by lobobinario** [aws-samples/aws-shield-advanced-rapid-deployment#1]
Just a feature. As most companies follow a naming convention for resources, provide the feature to pass lambda the desired Role name for creating the SRT role.

**Comment by olsonian** [comment]
hi lobobinario@
Apologize for not replying before, I apparently missed the notification for this issue/feature ask.  I just pushed a quick update make the role name for SRT access configurable as a CFN parameter.
